import { APP_PATHS } from './paths';

export const MAIN_MENU = [
  APP_PATHS.DASHBOARD,
  APP_PATHS.COLLECTION,
];

export const PROFILE_MENU = [
  APP_PATHS.PROFILE_PERSONAL_INFORMATION,
  APP_PATHS.CHANGE_PASSWORD,
  APP_PATHS.DANGER_ZONE,
];

export const COLLECTION_MENU = [
  APP_PATHS.COLLECTION_LIST_TV,
  APP_PATHS.COLLECTION_LIST_MOVIE,
];
