import { APP_PATHS } from './paths';

export const MAIN_MENU = [
  APP_PATHS.DASHBOARD,
  APP_PATHS.COLLECTIONS,
];

export const PROFILE_MENU = [
  APP_PATHS.PROFILE_PERSONAL_INFORMATION,
  APP_PATHS.PROFILE_CHANGE_PASSWORD,
  APP_PATHS.PROFILE_DANGER_ZONE,
];

export const COLLECTIONS_MENU = [
  APP_PATHS.COLLECTIONS_TV,
  APP_PATHS.COLLECTIONS_MOVIE,
];

export const COLLECTIONS_EDIT_MENU = [
  APP_PATHS.COLLECTIONS_EDIT_TV,
  APP_PATHS.COLLECTIONS_EDIT_MOVIE,
];
