import {
  red,
  pink,
  purple,
  deepPurple,
  indigo,
  blue,
  lightBlue,
  cyan,
  green,
  lightGreen,
  lime,
  yellow,
  amber,
  orange,
  deepOrange,
  brown,
  grey,
  blueGrey,
} from '@material-ui/core/colors';

export const COLOR_OPTIONS = [
  { id: red[500], label: 'colors.red' },
  { id: pink[500], label: 'colors.pink' },
  { id: purple[500], label: 'colors.purple' },
  { id: deepPurple[500], label: 'colors.deepPurple' },
  { id: indigo[500], label: 'colors.indigo' },
  { id: blue[700], label: 'colors.blue' },
  { id: lightBlue[500], label: 'colors.lightBlue' },
  { id: cyan[700], label: 'colors.cyan' },
  { id: green[600], label: 'colors.green' },
  { id: lightGreen[500], label: 'colors.lightGreen' },
  { id: lime[500], label: 'colors.lime' },
  { id: yellow[500], label: 'colors.yellow' },
  { id: amber[700], label: 'colors.amber' },
  { id: orange[800], label: 'colors.orange' },
  { id: deepOrange[500], label: 'colors.deepOrange' },
  { id: brown[500], label: 'colors.brown' },
  { id: grey[600], label: 'colors.grey' },
  { id: blueGrey[500], label: 'colors.blueGrey' },
];

export default COLOR_OPTIONS;
